fix

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -5,13 +5,17 @@
 BUILD_DIR=${1:-}
 CACHE_DIR=${2:-}
 ENV_DIR=${3:-}
-BP_DIR=$(cd $(dirname ${0:-}); cd ..; pwd)
+BP_DIR=$(
+    cd $(dirname ${0:-})
+    cd ..
+    pwd
+)
 
 # Export DATABASE_URL at build time, mostly because Diesel is the best way to
 # do SQL in Rust right now, and Diesel will use it to generate code for the
 # database schema.
 if [ -e "$ENV_DIR/DATABASE_URL" ]; then
-  export DATABASE_URL="$(cat $ENV_DIR/DATABASE_URL)";
+    export DATABASE_URL="$(cat $ENV_DIR/DATABASE_URL)"
 fi
 
 # Set defaults for our configuration variables.  Stable Rust is sufficiently
@@ -34,8 +38,10 @@ RUST_INSTALL_DIESEL=0
 DIESEL_FLAGS=""
 # Default build flags to pass to `cargo build`.
 RUST_CARGO_BUILD_FLAGS="--release"
+echo "ENV DIR $ENV_DIR"
+echo "build flags = $(cat $ENV_DIR/RUST_CARGO_BUILD_FLAGS)"
 if [ -e "$ENV_DIR/RUST_CARGO_BUILD_FLAGS" ]; then
-   RUST_CARGO_BUILD_FLAGS="$(cat $ENV_DIR/RUST_CARGO_BUILD_FLAGS)";
+    RUST_CARGO_BUILD_FLAGS="$(cat $ENV_DIR/RUST_CARGO_BUILD_FLAGS)"
 fi
 
 # Load our toolchain configuration, if any was specified.
@@ -53,13 +59,13 @@ set -eu
 
 # Check our configuration options.
 if [ -z ${VERSION+x} ]; then
-  >&2 echo "failed: must set VERSION with rust-toolchain or RustConfig to indicate the Rust version."
-  exit 1
+    >&2 echo "failed: must set VERSION with rust-toolchain or RustConfig to indicate the Rust version."
+    exit 1
 fi
 
 # Notify users running old, unstable versions of Rust about how to deploy
 # successfully.
-if [ $RUST_SKIP_BUILD -ne 1  ] && ( [ ! -z ${CARGO_URL+x} ] || [ ! -f "$BUILD_DIR/$BUILD_PATH/Cargo.toml" ] ); then
+if [ $RUST_SKIP_BUILD -ne 1 ] && ([ ! -z ${CARGO_URL+x} ] || [ ! -f "$BUILD_DIR/$BUILD_PATH/Cargo.toml" ]); then
     >&2 cat <<EOF
 To deploy a modern Rust app, make sure you have a Cargo.toml file, and that
 you do not define CARGO_URL or CARGO_VERSION in RustConfig.  If you're
@@ -76,7 +82,7 @@ if [ ! -z ${URL+x} ]; then
     >&2 cat <<EOF
 heroku-pack-rust has switched to using rustup.  You no longer need a
 URL field in RustConfig. Instead, you should just specify a
-rustup-compatible version (such as `1.11`, `stable` or `nighty`) in VERSION.
+rustup-compatible version (such as $(1.11), $(stable) or $(nighty)) in VERSION.
 EOF
     exit 1
 fi
@@ -84,7 +90,7 @@ fi
 # Record our Rust build environment configuration in an export file, in
 # case another buildpack needs it to build Ruby gems that use Rust or
 # something like that.
-cat <<EOF > $BP_DIR/export
+cat <<EOF >$BP_DIR/export
 # Our rustup installation.
 export RUSTUP_HOME="$CACHE_DIR/multirust"
 
@@ -112,15 +118,15 @@ if [ -d "$CARGO_HOME" ]; then
     rustup default "$VERSION"
 else
     echo "-----> Downloading rustup"
-    curl https://sh.rustup.rs -sSf > rustup.sh
+    curl https://sh.rustup.rs -sSf >rustup.sh
     chmod u+x rustup.sh
     echo "-----> Using rustup to install Rust channel $VERSION"
     ./rustup.sh -y --default-toolchain "$VERSION"
     rm rustup.sh
 fi
 if [ ! -x "$CARGO_HOME/bin/rustc" ]; then
-  echo "failed: Cannot find Rust binaries at $CARGO_HOME"
-  exit 1
+    echo "failed: Cannot find Rust binaries at $CARGO_HOME"
+    exit 1
 fi
 
 # This is where we will cache our Rust output.  Note the suggestions at
@@ -129,28 +135,28 @@ fi
 export CARGO_TARGET_DIR="$CACHE_DIR/target"
 
 if [ $RUST_SKIP_BUILD -ne 1 ]; then
-  # Build our project (into CARGO_TARGET_DIR so we have caching) and copy it
-  # back to the source tree.  In theory, we could probably just copy the
-  # binary or do something clever with `cargo install`, but we haven't
-  # figured that out yet.
-  #
-  # To debug git issues:
-  #export RUST_LOG="cargo::sources::git=debug"
-  # To debug compiler and linking issues, add `--verbose`.
-  echo "-----> Building application using Cargo"
-  cd "$BUILD_DIR/$BUILD_PATH"
-  rm -rf target/
-  echo "build flags $RUST_CARGO_BUILD_FLAGS"
-  cargo build "$RUST_CARGO_BUILD_FLAGS"
-  mkdir -p target/release
-  find "$CARGO_TARGET_DIR/release" -maxdepth 1 -type f -executable -exec cp -a -t target/release {} \;
+    # Build our project (into CARGO_TARGET_DIR so we have caching) and copy it
+    # back to the source tree.  In theory, we could probably just copy the
+    # binary or do something clever with `cargo install`, but we haven't
+    # figured that out yet.
+    #
+    # To debug git issues:
+    #export RUST_LOG="cargo::sources::git=debug"
+    # To debug compiler and linking issues, add `--verbose`.
+    echo "-----> Building application using Cargo"
+    cd "$BUILD_DIR/$BUILD_PATH"
+    rm -rf target/
+    echo "build flags $RUST_CARGO_BUILD_FLAGS"
+    cargo build "$RUST_CARGO_BUILD_FLAGS"
+    mkdir -p target/release
+    find "$CARGO_TARGET_DIR/release" -maxdepth 1 -type f -executable -exec cp -a -t target/release {} \;
 else
-  echo "-----> Skipping Cargo build"
+    echo "-----> Skipping Cargo build"
 fi
 
 # Install diesel so we can use it for migrations
 if [ $RUST_INSTALL_DIESEL -eq 1 ]; then
-  echo "-----> Installing diesel"
-  cargo install diesel_cli $DIESEL_FLAGS || echo "already installed"
-  cp $(which diesel) target/release/
+    echo "-----> Installing diesel"
+    cargo install diesel_cli $DIESEL_FLAGS || echo "already installed"
+    cp $(which diesel) target/release/
 fi
